In [1]:
import pandas as pd

# Load all the necessary datasets
customers = pd.read_csv('data/olist_customers_dataset.csv')
orders = pd.read_csv('data/olist_orders_dataset.csv')
order_items = pd.read_csv('data/olist_order_items_dataset.csv')
order_payments = pd.read_csv('data/olist_order_payments_dataset.csv')
order_reviews = pd.read_csv('data/olist_order_reviews_dataset.csv')
products = pd.read_csv('data/olist_products_dataset.csv')
sellers = pd.read_csv('data/olist_sellers_dataset.csv')
category_translation = pd.read_csv('data/product_category_name_translation.csv')

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [2]:
# Merge orders with customers
data = pd.merge(orders, customers, on='customer_id')

# Merge with order items
data = pd.merge(data, order_items, on='order_id')

# Merge with order payments
data = pd.merge(data, order_payments, on='order_id')

# Merge with order reviews
data = pd.merge(data, order_reviews, on='order_id')

# Merge with products and their English category names
product_info = pd.merge(products, category_translation, on='product_category_name')
data = pd.merge(data, product_info, on='product_id')

# Merge with sellers
data = pd.merge(data, sellers, on='seller_id')

data.shape

(115609, 40)

In [3]:
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,housewares,9350,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,housewares,9350,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,housewares,9350,maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,178.0,1.0,400.0,19.0,13.0,19.0,perfumery,31570,belo horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,232.0,1.0,420.0,24.0,19.0,21.0,auto,14840,guariba,SP

In [4]:
product_info.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

DATA CLEANING & PREPARATION

In [5]:
# Convert all timestamp columns to datetime objects
timestamp_cols = [
    'order_purchase_timestamp', 'order_approved_at',
    'order_delivered_carrier_date', 'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in timestamp_cols:
    data[col] = pd.to_datetime(data[col], errors='coerce') # 'coerce' will turn errors into NaT (Not a Time)

# Handle critical missing values
# We also remove orders without a valid purchase timestamp.
data.dropna(subset=['order_purchase_timestamp', 'order_delivered_customer_date'], inplace=True)

print("Data types corrected and missing values handled.")
data.info()

Data types corrected and missing values handled.
<class 'pandas.core.frame.DataFrame'>
Index: 113209 entries, 0 to 115608
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113209 non-null  object
 1   customer_id                    113209 non-null  object
 2   order_status                   113209 non-null  object
 3   order_purchase_timestamp       113209 non-null  datetime64[ns]
 4   order_approved_at              113195 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113208 non-null  datetime64[ns]
 6   order_delivered_customer_date  113209 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113209 non-null  datetime64[ns]
 8   customer_unique_id             113209 non-null  object
 9   customer_zip_code_prefix       113209 non-null  int64
 10  customer_city                  113209 non-null  object
 11  customer_state                 113209 non-null  object
 12  order_item_id                  113209 non-null  int64
 13  product_id                     113209 non-null  object
 14  seller_id                      113209 non-null  object
 15  shipping_limit_date            113209 non-null  object
 16  price                          113209 non-null  float64
 17  freight_value                  113209 non-null  float64
 18  payment_sequential             113209 non-null  int64
 19  payment_type                   113209 non-null  object
 20  payment_installments           113209 non-null  int64
 21  payment_value                  113209 non-null  float64
 22  review_id                      113209 non-null  object
 23  review_score                   113209 non-null  int64
 24  review_comment_title           13493 non-null   object
 25  review_comment_message         47367 non-null   object
 26  review_creation_date           113209 non-null  object
 27  review_answer_timestamp        113209 non-null  object
 28  product_category_name          113209 non-null  object
 29  product_name_lenght            113209 non-null  float64
 30  product_description_lenght     113209 non-null  float64
 31  product_photos_qty             113209 non-null  float64
 32  product_weight_g               113208 non-null  float64
 33  product_length_cm              113208 non-null  float64
 34  product_height_cm              113208 non-null  float64
 35  product_width_cm               113208 non-null  float64
 36  product_category_name_english  113209 non-null  object
 37  seller_zip_code_prefix         113209 non-null  int64
 38  seller_city                    113209 non-null  object
 39  seller_state                   113209 non-null  object
dtypes: datetime64[ns](5), float64(10), int64(6), object(19)
memory usage: 35.4+ MB

FEATURE ENGINEERING

In [6]:
# --- Feature 1: Delivery Time & Delay ---
data['delivery_time'] = (data['order_delivered_customer_date'] - data['order_purchase_timestamp']).dt.days
data['estimated_delivery_time'] = (data['order_estimated_delivery_date'] - data['order_purchase_timestamp']).dt.days
data['delivery_delay'] = data['delivery_time'] - data['estimated_delivery_time']

In [7]:
# --- Feature 2: RFM Metrics & Churn ---
# Find the last order date in the dataset to calculate recency from
snapshot_date = data['order_purchase_timestamp'].max() + pd.DateOffset(days=1)

# Group data by customer
customer_data = data.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'payment_value': 'sum'
})

# Rename columns for clarity
customer_data.rename(columns={
    'order_purchase_timestamp': 'recency',
    'order_id': 'frequency',
    'payment_value': 'monetary'
}, inplace=True)

# --- Feature 3: Churn Variable ---
# Define churn: A customer is churned if they haven't purchased in 180 days (6 months)
customer_data['is_churned'] = (customer_data['recency'] > 180).astype(int)


# --- Merge RFM & Churn data back into the main dataframe ---
# This enriches our main dataset with customer-level predictive features
data = pd.merge(data, customer_data, on='customer_unique_id')


data[['customer_unique_id', 'delivery_time', 'delivery_delay', 'recency', 'frequency', 'monetary', 'is_churned']].head()

,customer_unique_id,delivery_time,delivery_delay,recency,frequency,monetary,is_churned
0,7c396fd4830fd04220f754e42b4e5bff,8,-7,332,2,82.82,1
1,7c396fd4830fd04220f754e42b4e5bff,8,-7,332,2,82.82,1
2,7c396fd4830fd04220f754e42b4e5bff,8,-7,332,2,82.82,1
3,af07308b275d755c9edb36a90c618231,13,-6,36,1,141.46,0
4,3a653a41f6f9fc3d2a113cf8398680e8,9,-17,22,1,179.12,0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113209 entries, 0 to 113208
Data columns (total 47 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113209 non-null  object
 1   customer_id                    113209 non-null  object
 2   order_status                   113209 non-null  object
 3   order_purchase_timestamp       113209 non-null  datetime64[ns]
 4   order_approved_at              113195 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113208 non-null  datetime64[ns]
 6   order_delivered_customer_date  113209 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113209 non-null  datetime64[ns]
 8   customer_unique_id             113209 non-null  object
 9   customer_zip_code_prefix       113209 non-null  int64
 10  customer_city                  113209 non-null  object
 11  customer_state                 113209 non-null  object
 12  order_item_id                  113209 non-null  int64
 13  product_id                     113209 non-null  object
 14  seller_id                      113209 non-null  object
 15  shipping_limit_date            113209 non-null  object
 16  price                          113209 non-null  float64
 17  freight_value                  113209 non-null  float64
 18  payment_sequential             113209 non-null  int64
 19  payment_type                   113209 non-null  object
 20  payment_installments           113209 non-null  int64
 21  payment_value                  113209 non-null  float64
 22  review_id                      113209 non-null  object
 23  review_score                   113209 non-null  int64
 24  review_comment_title           13493 non-null   object
 25  review_comment_message         47367 non-null   object
 26  review_creation_date           113209 non-null  object
 27  review_answer_timestamp        113209 non-null  object
 28  product_category_name          113209 non-null  object
 29  product_name_lenght            113209 non-null  float64
 30  product_description_lenght     113209 non-null  float64
 31  product_photos_qty             113209 non-null  float64
 32  product_weight_g               113208 non-null  float64
 33  product_length_cm              113208 non-null  float64
 34  product_height_cm              113208 non-null  float64
 35  product_width_cm               113208 non-null  float64
 36  product_category_name_english  113209 non-null  object
 37  seller_zip_code_prefix         113209 non-null  int64
 38  seller_city                    113209 non-null  object
 39  seller_state                   113209 non-null  object
 40  delivery_time                  113209 non-null  int64
 41  estimated_delivery_time        113209 non-null  int64
 42  delivery_delay                 113209 non-null  int64
 43  recency                        113209 non-null  int64
 44  frequency                      113209 non-null  int64
 45  monetary                       113209 non-null  float64
 46  is_churned                     113209 non-null  int64
dtypes: datetime64[ns](5), float64(11), int64(12), object(19)
memory usage: 40.6+ MB

In [ ]:
# Save the prepared data to a new file to be used for modeling
data.to_csv('olist_prepared_dataset.csv', index=False)

print("Prepared dataset saved to 'olist_prepared_dataset.csv'")

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


geolocation = pd.read_csv('data/olist_geolocation_dataset.csv')
df = pd.read_csv('data/olist_prepared_dataset.csv')

geolocation_agg = geolocation.groupby('geolocation_zip_code_prefix').agg({
    'geolocation_lat': 'mean',
    'geolocation_lng': 'mean'
}).reset_index()


df_geo = pd.merge(
    df,
    geolocation_agg,
    left_on='customer_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left' # Use a left join to keep all original orders
)


df_geo.to_csv('data/olist_prepared_dataset.csv', index=False)